name: laravel-lang-pt-PT

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create a new project
      run: composer create-project --prefer-dist laravel/laravel blog

    - name: Install laravel-lang-pt-PT
      run: composer require gook-ws/laravel-lang-pt-PT
      working-directory: ./blog

    - name: Publish translation
      run: php artisan vendor:publish --tag=laravel-lang-pt-PT
      working-directory: ./blog

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
